// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-quiz.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { quizQuestions, profiles } from "npm:@/lib/quizData";
var get_quiz_default = defineTool({
  name: "get_stoffwechsel_quiz",
  title: "Get Stoffwechsel Quiz",
  description: "Returns the full 6-question Stoffwechsel-Quiz (questions + answer options with profile mapping) and the three metabolism profile definitions (A: gestresster Stoffwechsel, B: unterversorgter Fettstoffwechsel, C: \xFCberangepasster Di\xE4t-Stoffwechsel).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({ questions: quizQuestions, profiles }, null, 2)
      }
    ],
    structuredContent: { questions: quizQuestions, profiles }
  })
});

// src/lib/mcp/tools/evaluate-quiz.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
import { calculateResult, profiles as profiles2 } from "npm:@/lib/quizData";
var evaluate_quiz_default = defineTool2({
  name: "evaluate_stoffwechsel_quiz",
  title: "Evaluate Stoffwechsel Quiz",
  description: "Given the counts of A/B/C answers picked in the Stoffwechsel-Quiz, determines the resulting metabolism profile (A, B, or C) and returns its full description. Tiebreaker priority: C > A > B.",
  inputSchema: {
    a: z.number().int().min(0).describe("Number of profile A answers picked."),
    b: z.number().int().min(0).describe("Number of profile B answers picked."),
    c: z.number().int().min(0).describe("Number of profile C answers picked.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ a, b, c }) => {
    const scores = { A: a, B: b, C: c };
    const winner = calculateResult(scores);
    const profile = profiles2[winner];
    return {
      content: [
        {
          type: "text",
          text: `Profil ${winner} \u2013 ${profile.name}

${profile.fullResult.description}`
        }
      ],
      structuredContent: { profileId: winner, profile }
    };
  }
});

// src/lib/mcp/tools/calorie-calculator.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { calculateAll } from "npm:@/lib/calorieCalculator";
var calorie_calculator_default = defineTool3({
  name: "calorie_calculator",
  title: "Kalorienrechner (Mifflin-St Jeor + Harris-Benedict)",
  description: "Calculates BMI, BMR (average of Mifflin-St Jeor and Harris-Benedict), TDEE, target calories, and macro split (protein / fat / carbs) for the given person. Same formulas used by Philipp's Biohack Kalorienrechner.",
  inputSchema: {
    gender: z2.enum(["male", "female"]),
    age: z2.number().int().min(10).max(120),
    weight: z2.number().min(20).max(400).describe("Body weight in kg."),
    height: z2.number().min(100).max(250).describe("Height in cm."),
    targetWeight: z2.number().min(20).max(400).optional().describe("Optional target weight in kg. Only used for protein calculation when BMI >= 30."),
    activityFactor: z2.number().min(1).max(2.5).describe("PAL activity factor, e.g. 1.2 sedentary, 1.375 light, 1.55 moderate, 1.725 heavy."),
    goal: z2.enum(["maintenance", "moderate", "aggressive"]),
    proteinFactor: z2.enum(["2.0", "2.2", "2.4"]).describe("Protein grams per kg of reference weight.").transform((v) => Number(v)),
    fatMode: z2.enum(["minimum", "standard"])
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const result = calculateAll(input);
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { ...result }
    };
  }
});

// src/lib/mcp/tools/metabolism-check.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { evaluateCheck, questions, levelData } from "npm:@/lib/metabolicCheck";
var metabolism_check_default = defineTool4({
  name: "metabolism_reset_check",
  title: "Stoffwechsel-Reset Check",
  description: "Evaluates the 8-question Stoffwechsel-Reset Check. Pass an array of 8 booleans (index-aligned with the questions). Returns total score, level (0-2), per-area breakdown, and the matching recommendation.",
  inputSchema: {
    answers: z3.array(z3.boolean()).length(8).describe("Array of exactly 8 yes/no answers, one per question in the fixed order.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ answers }) => {
    const map = {};
    answers.forEach((v, i) => map[i] = v);
    const result = evaluateCheck(map);
    const recommendation = levelData[result.level];
    return {
      content: [
        {
          type: "text",
          text: `${recommendation.title}

${recommendation.text}`
        }
      ],
      structuredContent: { ...result, questions, recommendation }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "philipps-biohack-mcp",
  title: "Philipp's Biohack \u2013 Stoffwechsel Tools",
  version: "0.1.0",
  instructions: "Public tools from Philipp's Biohack. Use `get_stoffwechsel_quiz` to fetch the 6-question metabolism quiz and profile definitions, `evaluate_stoffwechsel_quiz` to determine the resulting profile from A/B/C answer counts, `calorie_calculator` for BMR/TDEE/macros using the same formulas as the site, and `metabolism_reset_check` to score the 8-question Reset Check.",
  tools: [get_quiz_default, evaluate_quiz_default, calorie_calculator_default, metabolism_check_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
